version: '3.1'

services:
  db:
    container_name: udemy-master-fullstack-db
    image: postgres:14.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udemy-master-fullstack

volumes:
  pgdata:
    name: udemy-master-fullstack
